[build]
  command   = "npm install"
  publish   = "."
  functions = "netlify/functions"

[[headers]]
  for = "/OneSignalSDKWorker.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"
